let agora = new Date()
let hora = agora.getHours()
console.log(`Agora são ${hora} horas`)
if (hora > 0 && hora < 5)
    console.log('Boa madrugada!')
else if (hora < 12)
    console.log('Bom dia!')
else if (hora <= 17)
    console.log('Boa tarde!')
else if (hora <= 24)
    console.log('Boa noite!')

